FROM python:3.10.5

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

RUN cd google-images-download && python setup.py install
RUN mkdir downloads
RUN apt-get update

CMD ["python3", "main.py"]